version: "3"

services:
  rsync_client:
    restart: on-failure
    image: guenterbailey/rsync-client:bookworm
    volumes:
      - ./config:/config
      - roothome:/root:rw
    command: "ls -lah /root/.ssh/"

volumes:
  roothome:
